# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e623b9f2f355fb536291fc4707d56a5054dba52b204c840d50240a6a5b9ca3ca9d61ca742e83d09cf1b8e645332e996bffa057731dd7865f97988760489cc5b8
  facebook_key: 1647574085518034
  facebook_secret: 9cc269e6f0666cd8c5fa7f903b5f66b6
  google_key: 1011141767497-ko2efio3b9i9qbf92ife34u5898nuluk.apps.googleusercontent.com
  google_secret: ySNwdyBI0zjrkupcU4AcMyoh
  twitter_key: P9wYG9zd0yj3MUdfl4JZufUen
  twitter_secret: kay3aZ3HYwJzSoAqZuLIXPj3uNLACQppQa2KZ1sLLMxFVfoZOn

test:
  secret_key_base: 7aa177fe4ad9c10f1a20a0cc98dea35c4d0cb4ac6d72a7103a6bcbbad302e2f86fe56643b3aad54fe9dfb785303bfbc5f251f5cedc2a98377f9eeb7b5a4e52a9
  facebook_key: 1647574085518034
  facebook_secret: 9cc269e6f0666cd8c5fa7f903b5f66b6
  google_key: 1011141767497-ko2efio3b9i9qbf92ife34u5898nuluk.apps.googleusercontent.com
  google_secret: ySNwdyBI0zjrkupcU4AcMyoh
  twitter_key: P9wYG9zd0yj3MUdfl4JZufUen
  twitter_secret: kay3aZ3HYwJzSoAqZuLIXPj3uNLACQppQa2KZ1sLLMxFVfoZOn

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: 819486981482215
  facebook_secret: 8dedcdb68a2ea7b1b6e0328aee2b6b68
  google_key: 302216554740-2s5pks5n2qavkjjc9akrsaia9ug89ha7.apps.googleusercontent.com
  google_secret: 15I_5a2-WM-ATDYglmzmi_z-
  twitter_key: KKFx1D6qqg0sIc0SYMBgT3qut
  twitter_secret: GyUuVsYnBFY9oMBEBC4aIRA9KTSRS5FT2isUdqXXfe2DYlMYQp
